name: 'Deploy a Tenanted Release in Octopus Deploy'
description: 'GitHub Action to deploy a release in Octopus Deploy'
author: 'Octopus Deploy'
branding:
  color: 'blue'
  icon: 'package'

inputs:
  project:
    description: 'The name of the project associated with this release.'
    required: true
  release_number:
    description: 'The number for the release to deploy.'
    required: true
  environment:
    description: 'The environment name to deploy to.'
    required: true
  tenants:
    description: 'A multi-line list of tenant names to deploy to.'
  tenant_tags:
    description: 'A multi-line list of tenant tags (canonical names) to use to locate tenants to deploy to.'
  use_guided_failure:
    default: false
    description: 'Whether to use guided failure mode if errors occur during the deployment.'
  variables:
    description: 'A multi-line list of prompted variable values. Format: name:value'
  server:
    description: 'The instance URL hosting Octopus Deploy (i.e. "https://octopus.example.com/"). The instance URL is required, but you may also use the OCTOPUS_URL environment variable.'
  api_key:
    description: 'The API key used to access Octopus Deploy. One of API key or Access Token are required, but you may also use the OCTOPUS_API_KEY environment variable. It is strongly recommended that this value retrieved from a GitHub secret.'
  access_token:
    description: 'The access token used to access Octopus Deploy. One of API key or Access Token are required, to obtain an access token please use the `OctopusDeploy/login` action. You may also use the OCTOPUS_ACCESS_TOKEN environment variable if you are obtaining a token another way.'
  space:
    description: 'The name of a space within which this command will be executed. The space name is required, but you may also use the OCTOPUS_SPACE environment variable.'

outputs:
  server_tasks:
    description: 'JSON string for an array of objects having a `serverTaskId` and an `tenantName`'

runs:
  using: 'node16'
  main: 'dist/index.js'
